[package]
name = "fozzylang_unsafe_lab"
version = "0.1.0"

[[target.bin]]
name = "fozzylang_unsafe_lab"
path = "src/main.fzy"

[ffi]
panic_boundary = "error"

[link]
libs = ["hashkernels"]
search = ["./cbuild"]

[unsafe]
contracts = "compiler"
enforce_dev = false
enforce_verify = true
enforce_release = true
deny_unsafe_in = []
allow_unsafe_in = []
